/**
 * Test Utilities for Aztec Liquid Staking Integration Tests
 * 
 * This module provides helper functions for deploying contracts,
 * creating test accounts, and common test operations.
 */

import {
  AccountWallet,
  AztecAddress,
  Fr,
  createAccount,
  getContractInstanceFromDeployParams,
} from '@aztec/aztec.js';
import { pxe, TEST_CONFIG } from './setup.js';

// ============ CONTRACT DEPLOYMENT HELPERS ============

/**
 * Deploy all staking contracts in the correct order
 * Returns deployed contract instances
 */
export async function deployAllContracts(admin: AccountWallet) {
  console.log('Deploying contracts...');
  
  // Note: These imports will work after contracts are compiled
  // and artifacts are generated by aztec-nargo
  
  // 1. Deploy StakedAztecToken
  // const stakedToken = await StakedAztecTokenContract.deploy(
  //   admin,
  //   admin.getAddress()
  // ).send().deployed();
  
  // 2. Deploy ValidatorRegistry
  // 3. Deploy WithdrawalQueue
  // 4. Deploy VaultManager
  // 5. Deploy RewardsManager
  // 6. Deploy LiquidStakingCore
  
  // 7. Configure contract addresses
  // await liquidStakingCore.methods.set_staked_aztec_token(stakedToken.address).send().wait();
  // ... etc
  
  // Placeholder until contracts are compiled
  throw new Error(
    'Contract artifacts not available. Compile contracts with aztec-nargo first.'
  );
}

// ============ ACCOUNT HELPERS ============

/**
 * Create a test account with some initial balance
 */
export async function createTestAccount(): Promise<AccountWallet> {
  const account = await createAccount(pxe);
  console.log(`Created test account: ${account.getAddress().toString()}`);
  return account;
}

/**
 * Create multiple test accounts
 */
export async function createTestAccounts(count: number): Promise<AccountWallet[]> {
  const accounts: AccountWallet[] = [];
  for (let i = 0; i < count; i++) {
    accounts.push(await createTestAccount());
  }
  return accounts;
}

// ============ AUTHWIT HELPERS ============

/**
 * Create AuthWit for token transfer
 * This is required before calling deposit functions
 */
export async function createTransferAuthWit(
  wallet: AccountWallet,
  tokenAddress: AztecAddress,
  spender: AztecAddress,
  amount: bigint,
  nonce: Fr
): Promise<void> {
  // Note: Implementation depends on actual token contract interface
  // This is a placeholder showing the pattern
  
  // const action = token.methods.transfer_in_public(
  //   wallet.getAddress(),
  //   spender,
  //   amount,
  //   nonce
  // );
  // const authWit = await wallet.createAuthWit({ caller: spender, action });
  // await wallet.addAuthWitness(authWit);
  
  console.log(`AuthWit created for ${amount} tokens from ${wallet.getAddress()}`);
}

// ============ CONVERSION HELPERS ============

/**
 * Convert AZTEC amount to stAZTEC based on exchange rate
 */
export function aztecToStAztec(aztecAmount: bigint, exchangeRate: bigint): bigint {
  return (aztecAmount * 10000n) / exchangeRate;
}

/**
 * Convert stAZTEC amount to AZTEC based on exchange rate
 */
export function stAztecToAztec(stAztecAmount: bigint, exchangeRate: bigint): bigint {
  return (stAztecAmount * exchangeRate) / 10000n;
}

/**
 * Calculate protocol fee
 */
export function calculateFee(amount: bigint, feeBps: bigint): bigint {
  return (amount * feeBps) / 10000n;
}

// ============ ASSERTION HELPERS ============

/**
 * Assert balance is within expected range (accounting for gas)
 */
export function assertBalanceApprox(
  actual: bigint,
  expected: bigint,
  tolerance: bigint = 1000000000000000n // 0.001 tokens
): void {
  const diff = actual > expected ? actual - expected : expected - actual;
  if (diff > tolerance) {
    throw new Error(
      `Balance mismatch: expected ${expected}, got ${actual} (diff: ${diff})`
    );
  }
}

/**
 * Assert exchange rate is higher than previous
 */
export function assertRateIncreased(
  previousRate: bigint,
  currentRate: bigint
): void {
  if (currentRate <= previousRate) {
    throw new Error(
      `Exchange rate should increase: was ${previousRate}, now ${currentRate}`
    );
  }
}

// ============ TIMING HELPERS ============

/**
 * Wait for a specific number of blocks
 */
export async function waitBlocks(count: number): Promise<void> {
  console.log(`Waiting for ${count} blocks...`);
  // In sandbox, blocks are produced on demand
  // This would be implemented based on sandbox's mining behavior
  await new Promise(resolve => setTimeout(resolve, count * 1000));
}

/**
 * Advance time in sandbox (for testing unbonding periods)
 */
export async function advanceTime(seconds: number): Promise<void> {
  console.log(`Advancing time by ${seconds} seconds...`);
  // Note: Sandbox may have specific methods for time manipulation
  // This is a placeholder
}

// ============ LOGGING HELPERS ============

/**
 * Log contract state for debugging
 */
export async function logContractState(
  contractName: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  contract: any
): Promise<void> {
  console.log(`\\n=== ${contractName} State ===`);
  // Would call view functions and log state
  console.log('(Contract state logging not implemented)');
}

/**
 * Format token amount for display
 */
export function formatTokenAmount(amount: bigint): string {
  const tokens = Number(amount) / 1e18;
  return `${tokens.toLocaleString()} tokens`;
}
