import type { DocumentRecord } from "./contracts";
import type { exportDocumentBundle } from "./export";
import type { evaluateReadiness } from "./readiness";

type ExportBundle = ReturnType<typeof exportDocumentBundle>;
type ReadinessReport = ReturnType<typeof evaluateReadiness>;

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "specforge-starter";
}

function toList(value: string | undefined) {
  return (value ?? "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

export function buildStarterTemplate(
  document: DocumentRecord,
  exportBundle: ExportBundle,
  readinessReport: ReadinessReport | null,
) {
  const packageName = slugify(document.title);
  const goals = toList(document.metadata.goals);
  const tasks = toList(document.metadata.tasks);
  const constraints = toList(document.metadata.constraints);
  const successSignals = toList(document.metadata.success_signals);
  const status = readinessReport?.status ?? "drafting";
  const confidence = Math.max(0.35, Math.min(0.98, (readinessReport?.score ?? 35) / 100));

  const packageJson = {
    name: packageName,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      dev: "tsx src/main.ts",
      build: "tsc -p tsconfig.json",
      start: "node dist/main.js",
    },
    devDependencies: {
      tsx: "^4.20.6",
      typescript: "^5.9.3",
    },
  };

  const specModule = [
    "export const spec = {",
    `  documentId: ${JSON.stringify(document.document_id)},`,
    `  title: ${JSON.stringify(document.title)},`,
    `  version: ${document.version},`,
    `  readiness: ${JSON.stringify(status)},`,
    `  goals: ${JSON.stringify(goals)},`,
    `  tasks: ${JSON.stringify(tasks)},`,
    `  constraints: ${JSON.stringify(constraints)},`,
    `  successSignals: ${JSON.stringify(successSignals)},`,
    "};",
    "",
    "export type Spec = typeof spec;",
  ].join("\n");

  const mainModule = [
    'import { spec } from "./spec.js";',
    "",
    'console.log(`Building from ${spec.title} (${spec.documentId})`);',
    'console.log(`Readiness: ${spec.readiness}`);',
    'console.log("Goals:");',
    'for (const goal of spec.goals) console.log(`- ${goal}`);',
    'console.log("Tasks:");',
    'for (const task of spec.tasks) console.log(`- ${task}`);',
    "",
    "// Replace this starter with a concrete app build for the selected template family.",
  ].join("\n");

  const readme = [
    `# ${document.title} Starter`,
    "",
    "Generated by SpecForge from the approved handoff bundle.",
    "",
    "## Why this exists",
    "",
    "This starter compresses the approved spec into a runnable TypeScript entrypoint so a coding agent or human can continue implementation without re-parsing every source document.",
    "",
    "## Next steps",
    "",
    ...[
      "npm install",
      "npm run dev",
      "Replace the starter implementation with the first vertical slice from the spec",
      "Keep the spec bundle nearby for patch review and acceptance criteria",
    ].map((line) => `- ${line}`),
  ].join("\n");

  return {
    template_id: "ts_cli_starter_v1",
    readiness_status: status,
    confidence,
    next_steps: [
      "Install dependencies and run the starter entrypoint.",
      "Implement the first task group from TASKS.md.",
      "Use PRD.md and SPEC.md as the authoritative build context.",
    ],
    files: {
      "package.json": JSON.stringify(packageJson, null, 2),
      "tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "NodeNext",
            moduleResolution: "NodeNext",
            outDir: "dist",
            rootDir: "src",
            strict: true,
            esModuleInterop: true,
          },
          include: ["src"],
        },
        null,
        2,
      ),
      "README.md": readme,
      "src/spec.ts": specModule,
      "src/main.ts": mainModule,
      "specforge/agent_spec.json": exportBundle.files["agent_spec.json"],
    },
  };
}
