#!/usr/bin/env bash
set -euo pipefail

GSTACK_REPO="${GSTACK_REPO:-https://github.com/garrytan/gstack.git}"
GSTACK_DIR="${GSTACK_DIR:-$HOME/.claude/skills/gstack}"
SHARED_SKILLS="${SHARED_SKILLS:-$HOME/.agents/skills}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC_SCRIPT="$SCRIPT_DIR/sync-shared-skills.sh"

if [[ -d "$GSTACK_DIR/.git" ]]; then
  echo "updating gstack in $GSTACK_DIR"
  git -C "$GSTACK_DIR" pull --ff-only
else
  echo "cloning gstack into $GSTACK_DIR"
  rm -rf "$GSTACK_DIR"
  git clone "$GSTACK_REPO" "$GSTACK_DIR"
fi

echo "running gstack setup"
(cd "$GSTACK_DIR" && ./setup)

mkdir -p "$SHARED_SKILLS"

# gstack runtime root (bin/, browse/, design/, etc.)
ln -sfn "$GSTACK_DIR" "$SHARED_SKILLS/gstack"

# Codex/OpenAI host skill docs generated by gstack setup.
CODEX_SKILL_DIR="$GSTACK_DIR/.agents/skills"
if [[ ! -d "$CODEX_SKILL_DIR" ]]; then
  echo "expected codex skill dir missing: $CODEX_SKILL_DIR" >&2
  exit 1
fi

for skill_path in "$CODEX_SKILL_DIR"/gstack-*; do
  [[ -e "$skill_path" ]] || continue
  name="$(basename "$skill_path")"
  ln -sfn "$skill_path" "$SHARED_SKILLS/$name"
done

if [[ ! -x "$SYNC_SCRIPT" ]]; then
  echo "sync script missing or not executable: $SYNC_SCRIPT" >&2
  exit 1
fi

echo "syncing shared skills into Claude/Codex homes"
"$SYNC_SCRIPT" "$SHARED_SKILLS"

echo "done"
echo "gstack root: $GSTACK_DIR"
echo "shared skills: $SHARED_SKILLS"
